############################
## CHANGE THESE
############################

baseURL: "https://benzebra.github.io"
title: benzebra

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
