############################
## Navbar
############################

main:
  - name: Home
    url: /
    weight: 10
  #- name: Blog
  #  url: /blog/
  #  weight: 30
  - name: About
    url: /about/
    weight: 30
  - name: Projects
    url: /wip/
    weight: 30
  - name: Contacts
    url: /contacts/
    weight: 30
